name: Rust CI & Release

# 触发条件：当推送到 main 分支或创建以 v 开头的 tag 时触发
on:
  push:
    branches:
      - main        # 推送到 main 分支时运行 CI（执行测试与构建）
    tags:
      - 'v*'         # 推送以 v 开头的 tag（如 v1.2.3）时运行 CI，也会触发发布

# 在所有步骤中启用彩色输出
env:
  CARGO_TERM_COLOR: always

jobs:
  # ───────────────────────────────
  # Linux 平台：构建、测试、打包、发布
  # ───────────────────────────────
  linux:
    runs-on: ubuntu-latest

    # 如果需要在集成测试里连接数据库，在同一个 Runner 上启动一个 Postgres 容器
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres          # 容器内 Postgres 用户名
          POSTGRES_PASSWORD: password      # 容器内 Postgres 密码
          POSTGRES_DB: newsletter           # 容器内默认数据库名
        ports:
          - 5432:5432                       # 将容器的 5432 端口映射到宿主机 5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # 测试和迁移时会用到
      DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter
      # 测试、迁移阶段连接数据库所用的环境变量
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 用于发布 Release 的 GitHub Token，自动注入，无需手动配置

    steps:
      # ────────────────────────────────────────────────────
      # 1. 检出仓库代码
      # ────────────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v3
        # 将当前仓库代码拉取到 Runner 上

      # ────────────────────────────────────────────────────────────────────────
      # 2. 缓存 Cargo 的依赖与编译结果
      #
      #  - ~/.cargo/registry      包含已下载的 crates.io 索引与 crate 源码
      #  - ~/.cargo/git           包含 Git 依赖的缓存
      #  - target                  包含编译产物（多个配置：debug、release、测试二进制等）
      #
      # 这里的 key 使用 Cargo.lock 的哈希，确保当 lockfile 变动时才重新拉依赖。
      # restore-keys 保证在 lockfile 未改变时能命中回退缓存。
      # ────────────────────────────────────────────────────────────────────────
      - name: Cache Cargo registry and build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # ────────────────────────────────────────────────────────────────────────
      # 3. 安装 sqlx-cli（仅在需要跑迁移时使用）
      # ────────────────────────────────────────────────────────────────────────
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      # ────────────────────────────────────────────────────────────────────────
      # 4. 等待 Postgres 服务就绪（仅在集成测试场景）
      # ────────────────────────────────────────────────────────────────────────
      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -U postgres; then
              echo "Postgres is ready!"
              break
            else
              echo "Waiting for Postgres..."
              sleep 2
            fi
          done

      # ────────────────────────────────────────────────────
      # 4. 创建数据库并运行迁移（仅在集成测试场景）
      # ────────────────────────────────────────────────────
      - name: Create database & run migrations
        run: |
          # 尝试创建数据库，若已存在则忽略错误
          sqlx database create || echo "database already exists"
          # 对新创建的库运行 migrations/ 目录下所有迁移脚本
          sqlx migrate run

      # ────────────────────────────────────────────────────────────────────────
      # 6. 运行测试（包括单元测试与集成测试）
      #
      # 说明：
      #  - 缓存与上一步共享 target，所以如果依赖没变化，cargo test 会直接复用已编译的 crate
      #  - cargo test 会先拉取依赖、编译 debug+test 二进制，然后运行所有测试
      # ────────────────────────────────────────────────────────────────────────
      - name: Run tests
        run: cargo test --verbose
        # 执行所有测试用例，若有失败则 CI 报错

      # ────────────────────────────────────────────────────────────────────────
      # 7. 构建 Release 可执行文件
      #
      # 说明：
      #  - 由于 target 目录已缓存，cargo build --release 不会重头拉依赖，只会编译 release 二进制
      #  - 测试时编译过的 crate 库会被复用，可显著缩短编译时间
      # ────────────────────────────────────────────────────────────────────────
      - name: Build (release)
        run: cargo build --release
        # 生成优化后的可执行文件，输出到 target/release/

      # ────────────────────────────────────────────────────
      # 7. 打包 Linux 可执行文件（仅在推送 tag 时执行）
      # ────────────────────────────────────────────────────
      - name: Package (Linux)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p dist
          # 复制编译好的可执行文件到 dist 目录
          cp target/release/zero2prod dist/
          # 在文件名里包含 tag 名称和平台标识
          tar -czf zero2prod-${{ github.ref_name }}-linux-x86_64.tar.gz -C dist zero2prod

      # ────────────────────────────────────────────────────────────────────────
      # 9.（仅在推送 tag 时）上传 Linux 包到 GitHub Release
      # ────────────────────────────────────────────────────────────────────────
      - name: Upload Linux Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: zero2prod-${{ github.ref_name }}-linux-x86_64.tar.gz

  # ─────────────────────────────────────────────────────────────────────────────
  # Windows 平台：仅在推送 tag 时构建、打包、发布
  # ─────────────────────────────────────────────────────────────────────────────
  windows:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # ────────────────────────────────────────────────────────────────────────
      # 1. 检出仓库代码
      # ────────────────────────────────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v3

      # ────────────────────────────────────────────────────────────────────────
      # 2. 构建 Release 可执行文件（Windows）
      #
      # 说明：
      #  - 同样利用上面 Linux 任务缓存的 target 目录（跨 Runner 不共享缓存，Windows 自己会在首次构建时从 crates.io 拉依赖并编译）
      #  - 如果需要缩短第二次构建，可在此处单独添加 Windows 缓存步骤
      # ────────────────────────────────────────────────────────────────────────
      - name: Build (Windows)
        run: cargo build --release

      # ────────────────────────────────────────────────────────────────────────
      # 3. 打包 Windows 可执行文件
      # ────────────────────────────────────────────────────────────────────────
      - name: Package (Windows)
        run: |
          mkdir dist
          Copy-Item target\release\zero2prod.exe dist\
          Compress-Archive -Path dist\zero2prod.exe -DestinationPath zero2prod-${{ github.ref_name }}-windows-x86_64.zip

      # ────────────────────────────────────────────────────────────────────────
      # 4. 上传 Windows 包到 GitHub Release
      # ────────────────────────────────────────────────────────────────────────
      - name: Upload Windows Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: zero2prod-${{ github.ref_name }}-windows-x86_64.zip

  # ─────────────────────────────────────────────────────────────────────────────
  # macOS 平台：仅在推送 tag 时构建、打包、发布
  # ─────────────────────────────────────────────────────────────────────────────
  mac:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # ────────────────────────────────────────────────────────────────────────
      # 1. 检出仓库代码
      # ────────────────────────────────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v3

      # ────────────────────────────────────────────────────────────────────────
      # 2. 构建 Release 可执行文件（macOS）
      # ────────────────────────────────────────────────────────────────────────
      - name: Build (macOS)
        run: cargo build --release

      # ────────────────────────────────────────────────────────────────────────
      # 3. 打包 macOS 可执行文件
      # ────────────────────────────────────────────────────────────────────────
      - name: Package (macOS)
        run: |
          mkdir -p dist
          cp target/release/zero2prod dist/
          tar -czf zero2prod-${{ github.ref_name }}-macos-x86_64.tar.gz -C dist zero2prod

      # ────────────────────────────────────────────────────────────────────────
      # 4. 上传 macOS 包到 GitHub Release
      # ────────────────────────────────────────────────────────────────────────
      - name: Upload macOS Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: zero2prod-${{ github.ref_name }}-macos-x86_64.tar.gz